{{entity}}.index:
    pattern: /
    options:
        _controller: web\{{entity}}::read
        _title: Разводная страница
        _action: read
    defaults:
        condition: {enabled: true}
        sort: {_id: -1}
        limit: 10
        skip: 0
    methods: GET
    
{{entity}}.pagination:
    pattern: /page/{page}/
    options:
        _controller: web\{{entity}}::read
        _title: Постраничный вывод элементов
        _action: read
    defaults:
        condition: {enabled: true}
        sort: {_id: -1}
        limit: 10
        skip: 0
    methods: GET

{{entity}}.create:
    pattern: /create/
    options:
        _controller: web\{{entity}}::create
        _title: Создание элемента
        _action: create
    methods: POST

{{entity}}.read:
    pattern: /{_id}/
    options:
        _controller: web\{{entity}}::read
        _title: Просмотр элемента
        _action: read
    requirements:
        _id: ([0-9A-Za-z]){24}
    methods: GET

{{entity}}.update:
    pattern: /update/
    options:
        _controller: web\{{entity}}::update
        _title: Редактирование элемента
        _action: update
    methods: POST

{{entity}}.delete:
    pattern: /delete/
    options:
        _controller: web\{{entity}}::delete
        _title: Удаление элемента
        _action: delete
    methods: POST

{{entity}}.export:
    pattern: /export/
    options:
        _controller: web\{{entity}}::export
        _layout: null
        _title: Экспорт элементов
        _action: read
    defaults:
        sort: {_id: -1}
    methods: [GET,POST]